<?php
// Wordpress Dashboard WPSC Settings (under Advanced) check "Legacy page caching" and check "Late init"

function cca_enable_geoip_cachekey($key) {

		  $just_these = array();  // the list of country codes to be separately cached, this string is replaced/generated by the plugin 
			$cca_maxmindDataDirectory = "ccaMaxDataDirReplace"; // location of Maxmind data, this string is replaced/generated by the plugin 
			$ccwpsc_maxmindDirectory = "ccwpscMaxDirReplace"; // location of Maxmind script, this string is replaced/generated by the plugin 

// return info requested by Country Caching plugin
			if ($key == 'cca_version') return '0.0.3';
			if ($key == 'cca_options') return implode("," , $just_these);
			if ($key == 'cca_data') return $cca_maxmindDataDirectory;

// return original or modified key to Zen/QC
			$ISOcode = '';
			
// if Cloudflare provides GeoIP
      if ( ! empty($_SERVER["HTTP_CF_IPCOUNTRY"])) $ISOcode = $_SERVER["HTTP_CF_IPCOUNTRY"];  //Cloudflare GEOIP is enabled
      if ($ISOcode != 'XX' && ctype_alpha($ISOcode) && strlen($ISOcode) == 2 ) :
				if ( ! empty($just_these) && ! in_array($ISOcode,$just_these) ) :  // if we only want to separately cache some counties
					return $key;
				endif;
			  return $key . $ISOcode . '/';  // otherwise IP location not recognised - try Maxmind below
			endif;

// else use Maxmind for GeoIP
      $visitorIP = $_SERVER['REMOTE_ADDR'];
      if( filter_var($visitorIP, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4) ) :  //then server is IPV4
        $geoIPdb = 'GeoIP.dat';
      elseif ( filter_var($visitorIP, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) ) : $geoIPdb = 'GeoIPv6.dat';
			 else: return $key;
			endif;

			// different plugins each using their own copy of the Maxmind legacy script can cause WP to fail, we'll use a modified namespaced version to make ours "unique"
			if ( ! file_exists($ccwpsc_maxmindDirectory . 'ccwpsc_geoip.inc') || ! file_exists($cca_maxmindDataDirectory . $geoIPdb) ) :
			    return $key;
			endif;

			include_once($ccwpsc_maxmindDirectory . 'ccwpsc_geoip.inc');
  		$gi = \ccwpsc_max\geoip_open($cca_maxmindDataDirectory . $geoIPdb, GEOIP_STANDARD);  
      if ($geoIPdb == 'GeoIP.dat') :
				  $ISOcode = \ccwpsc_max\geoip_country_code_by_addr($gi, $visitorIP);
      else:
			   $ISOcode = \ccwpsc_max\geoip_country_code_by_addr_v6($gi, $visitorIP);
			endif;
      \ccwpsc_max\geoip_close($gi);
			
			// if the "just these" list exists only suffix the cache key with country code if it is in the list
      if (ctype_alpha($ISOcode)) :
				if ( empty($just_these) || in_array($ISOcode,$just_these) ):
			    $key = $key . $ISOcode . '/';
				endif;
			endif;
			return $key;
}
if (function_exists('add_cacheaction')) add_cacheaction( 'wp_cache_key', 'cca_enable_geoip_cachekey' );
?>